[package]
name = "tauri_template"
version = "0.1.0"
description = "A minimal Tauri application template"
authors = ["you"]
edition = "2021"

[lib]
name = "tauri_template_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png", "macos-private-api"] }
tauri-plugin-lilia = { git = "https://github.com/sena-nana/LiliaUI", rev = "fefcd3bc4a4a454276f2162bc21ab4faef14fd3f" }
tauri-plugin-store = "2"

[dev-dependencies]
serde_json = "1"

[profile.dev]
debug = "line-tables-only"
incremental = true
codegen-units = 256

[profile.dev.package."*"]
debug = false
opt-level = 1

[profile.release]
lto = "thin"
codegen-units = 1
strip = "debuginfo"
incremental = false
