changelog:
  categories:
    - title: 需求与功能
      labels:
        - enhancement
    - title: BUG 修复
      labels:
        - bug
    - title: 文档
      labels:
        - documentation
    - title: 其他改动
      labels:
        - "*"
